import { jsonResponse, errorResponse, optionsResponse } from "../roadmap/cors";

// ─── OPTIONS (CORS Preflight) ──────────────────────────────────────────────────

export async function OPTIONS() {
  return optionsResponse();
}

// ─── POST Handler ──────────────────────────────────────────────────────────────

export async function POST(req: Request) {
  try {
    const { query } = await req.json();

    if (!query || typeof query !== "string") {
      return errorResponse("Missing or invalid 'query' parameter.", undefined, 400);
    }

    const apiKey = process.env.HUGGINGFACE_API_KEY;
    
    if (!apiKey) {
      return errorResponse("Missing HUGGINGFACE_API_KEY environment variable.", undefined, 500);
    }

    const prompt = `Educational STEM illustration, highly detailed, scientific, high quality: ${query}`;
    
    // Call the Hugging Face Inference API
    const response = await fetch(
      `https://api-inference.huggingface.co/models/black-forest-labs/FLUX.1-schnell`,
      {
        method: "POST",
        headers: { 
          "Authorization": `Bearer ${apiKey}`,
          "Content-Type": "application/json" 
        },
        body: JSON.stringify({
          inputs: prompt
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      return errorResponse("Hugging Face API failed", `Status: ${response.status}. ${errorText}`, response.status);
    }

    // Hugging Face API returns binary image data directly
    const arrayBuffer = await response.arrayBuffer();
    const base64 = Buffer.from(arrayBuffer).toString("base64");

    if (!base64) {
      return errorResponse("No image generated by Hugging Face API", undefined, 400);
    }

    return jsonResponse({ base64 });
  } catch (error: unknown) {
    console.error("[image] Backend image generation error:", error);
    const message = error instanceof Error ? error.message : "Internal Server Error";
    return errorResponse("Internal Server Error", message, 500);
  }
}
