import { jsonResponse, errorResponse, optionsResponse } from "../roadmap/cors";

// ─── OPTIONS (CORS Preflight) ──────────────────────────────────────────────────

export async function OPTIONS() {
  return optionsResponse();
}

// ─── POST Handler ──────────────────────────────────────────────────────────────

export async function POST(req: Request) {
  try {
    const { query } = await req.json();

    if (!query || typeof query !== "string") {
      return errorResponse("Missing or invalid 'query' parameter.", undefined, 400);
    }

    // Support both the standard AI SDK env var and the specific one requested
    const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY || process.env.GEMINI_API_KEY;
    
    if (!apiKey) {
      return errorResponse("Missing GEMINI_API_KEY environment variable.", undefined, 500);
    }

    const prompt = `Educational STEM illustration, highly detailed, scientific, high quality: ${query}`;
    
    // Call the Gemini Nano Banana endpoint
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-image:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: prompt }]
          }],
          generationConfig: {
            candidateCount: 1
          }
        }),
      }
    );

    if (!response.ok) {
      return errorResponse("Gemini API failed", `Status: ${response.status}`, response.status);
    }

    const data = await response.json();
    let base64 = null;

    // Handle standard Gemini Image response schemas
    if (data.predictions && data.predictions[0]?.bytesBase64Encoded) {
      base64 = data.predictions[0].bytesBase64Encoded;
    } else if (data.candidates && data.candidates[0]?.content?.parts?.[0]?.inlineData?.data) {
      base64 = data.candidates[0].content.parts[0].inlineData.data;
    }

    if (!base64) {
      return errorResponse("No image generated by Gemini API", undefined, 400);
    }

    return jsonResponse({ base64 });
  } catch (error: unknown) {
    console.error("[image] Backend image generation error:", error);
    const message = error instanceof Error ? error.message : "Internal Server Error";
    return errorResponse("Internal Server Error", message, 500);
  }
}
